<?php

return [
    'hero_slide_1' => [
        'kicker' => 'Fresh • Premium • Beautifully Packed',
        'description' => 'Fruitwala Breakfast creates premium fruit baskets beautifully arranged in stylish boxes. Perfect for gifting, celebrations, corporate hampers, and healthy surprises — delivered fresh to your doorstep.',
        'btn_text' => 'Contact Us',
        'btn_url' => 'contact.php',
        'image' => 'assets/images/19.png',
    ],
    'hero_slide_2' => [
        'kicker' => 'Healthy Gifting Made Special',
        'description' => 'Surprise your loved ones with elegant fruit hampers made from handpicked premium fruits. Ideal for birthdays, anniversaries, festivals, and corporate gifting with same-day delivery available.',
        'btn_text' => 'Contact Us',
        'btn_url' => 'contact.php',
        'image' => 'assets/images/19.png',
    ],
    'reel_1' => [
        'video' => 'assets/videos/reels/reel1.mp4',
        'cover' => 'assets/videos/reels/cover1.png',
        'alt' => 'Fruitwala Reel',
    ],
    'reel_2' => [
        'video' => 'assets/videos/reels/reel2.mp4',
        'cover' => 'assets/videos/reels/cover2.png',
        'alt' => 'Fruitwala Reel',
    ],
    'reel_3' => [
        'video' => 'assets/videos/reels/reel3.mp4',
        'cover' => 'assets/videos/reels/cover3.jpg',
        'alt' => 'Fruitwala Reel',
    ],
    'reel_4' => [
        'video' => 'assets/videos/reels/reel4.mp4',
        'cover' => 'assets/videos/reels/cover4.jpg',
        'alt' => 'Fruitwala Reel',
    ],
    'quality_header' => [
        'badge' => 'FRESH • HEALTHY • HYGIENIC',
        'heading' => 'Why Choose Fruitwala Breakfast?',
    ],
    'quality_center' => [
        'video_src' => 'assets/videos/reels/reel5.mp4',
    ],
    'quality_l1' => [
        'title' => '<font>Premium</font> Fruit Quality',
        'desc' => 'We carefully select fresh, seasonal fruits to ensure every box is full of taste and nutrition.',
        'image' => 'assets/images/quality/qlty5.png',
    ],
    'quality_l2' => [
        'title' => '<font>Always</font> Freshly Packed',
        'desc' => 'Every fruit box is prepared fresh daily with proper hygiene and safe packaging.',
        'image' => 'assets/images/quality/qlty6.png',
    ],
    'quality_l3' => [
        'title' => '<font>100%</font> Natural Fruits',
        'desc' => 'No preservatives, no chemicals — just pure, fresh fruits for a healthy lifestyle.',
        'image' => 'assets/images/quality/qlty7.png',
    ],
    'quality_r1' => [
        'title' => 'Hygienic <font>Preparation</font>',
        'desc' => 'Our fruits are cleaned and packed in a hygienic environment for safe consumption.',
        'image' => 'assets/images/quality/qlty8.png',
    ],
    'quality_r2' => [
        'title' => 'Super <font>Healthy Choice</font>',
        'desc' => 'Perfect for breakfast, fitness diets, and healthy gifting options for loved ones.',
        'image' => 'assets/images/quality/qlty9.png',
    ],
    'quality_r3' => [
        'title' => 'Trusted <font>Quality Promise</font>',
        'desc' => 'We are committed to delivering fresh fruit boxes on time with consistent quality every day.',
        'image' => 'assets/images/quality/qlty10.png',
    ],
    'sale_sm_1' => [
        'title' => '<font>Daily</font> Fruit Breakfast',
        'subtitle' => 'Start Your Morning Healthy',
        'image' => 'assets/images/14.png',
        'link' => '#!',
    ],
    'sale_sm_2' => [
        'title' => '<font>Custom</font> Fruit Hampers',
        'subtitle' => 'Beautifully Packed for Every Occasion',
        'image' => 'assets/images/15.png',
        'link' => '#!',
    ],
    'product_ctg' => [
        'badge' => 'Healthy Offers on Every Order',
        'title' => 'Fresh, Seasonal & <font>Beautifully Packed Fruit Boxes</font>',
        'desc' => 'Fruitwala Breakfast delivers fresh fruit boxes and baskets prepared daily with care. Perfect for healthy breakfasts, office snacks, and premium fruit gifting.',
        'p1_title' => 'Only Fresh & Natural Fruits',
        'p1_desc' => 'We select high-quality seasonal fruits to ensure great taste, freshness, and nutrition in every box.',
        'p2_title' => 'Hygienic Packing & Safe Delivery',
        'p2_desc' => 'Every fruit box is cleaned, cut, and packed in a hygienic environment before doorstep delivery.',
        'btn_text' => 'Explore Fruit Boxes',
        'btn_url' => '#',
    ],
    'testimonial_1' => [
        'heading' => 'Freshness you can actually taste!',
        'body' => 'I order fruit boxes every week for my family breakfast. The fruits are always fresh, sweet, and beautifully packed. Fruitwala has become our healthy morning habit.',
        'author' => 'Neha Sharma – Mumbai',
        'image' => 'assets/images/testimonials/1.jpg',
    ],
    'testimonial_2' => [
        'heading' => 'Perfect for office fruit breaks',
        'body' => 'We started ordering Fruitwala boxes for our office staff. Everyone loves the variety and hygiene. It’s a great way to promote healthy snacking at work.',
        'author' => 'Rahul Mehta – Corporate Client',
        'image' => 'assets/images/testimonials/2.jpg',
    ],
    'testimonial_3' => [
        'heading' => 'Best fruit gifting option!',
        'body' => 'I gifted a premium fruit basket to my parents and they were so happy. The packaging was elegant and the fruits were top quality. Highly recommended.',
        'author' => 'Sanjay Verma – Pune',
        'image' => 'assets/images/testimonials/3.jpg',
    ],
    'testimonial_4' => [
        'heading' => 'Clean, healthy and always on time',
        'body' => 'I love how hygienic the fruit cutting and packing is. Delivery is always on time, which makes it easy for my daily breakfast routine.',
        'author' => 'Arjun Patel – Fitness Enthusiast',
        'image' => 'assets/images/testimonials/4.jpg',
    ],
    'testimonial_5' => [
        'heading' => 'A healthy start for my kids',
        'body' => 'My kids now prefer Fruitwala breakfast boxes over junk snacks. The fruit combinations are colorful, tasty, and perfect for school mornings.',
        'author' => 'Sneha Kulkarni – Homemaker',
        'image' => 'assets/images/testimonials/5.jpg',
    ],
    'gallery_left' => [
        'badge' => 'FRESH FROM FRUITWALA',
        'title' => 'From Farm to Your Doorstep',
        'desc' => 'Take a look at how we carefully select, pack, and deliver the freshest fruits every day. Quality, hygiene, and freshness are at the heart of everything we do.',
        'btn_text' => 'Explore More',
        'btn_url' => 'blogs.php',
    ],
    'gallery_mid' => [
        'title' => 'How Fruitwala Ensures Farm-Fresh Quality Every Morning',
        'link' => 'blog-details.php',
        'author' => 'Fruitwala Team',
        'time_label' => 'Updated Daily',
        'desc' => 'We source fruits directly from trusted farmers and inspect every batch before it reaches your home.',
        'image' => 'assets/images/15.png',
    ],
    'gallery_side_1' => [
        'thumb' => 'assets/images/5.jpg',
        'title' => '5 Benefits of Eating Seasonal Fruits',
        'meta1' => 'Fruitwala',
        'meta2' => 'Health Tips',
        'link' => '#',
    ],
    'gallery_side_2' => [
        'thumb' => 'assets/images/7.jpg',
        'title' => 'Why Fresh-Cut Fruits Taste Better',
        'meta1' => 'Fruitwala',
        'meta2' => 'Freshness Guide',
        'link' => '#',
    ],
    'gallery_side_3' => [
        'thumb' => 'assets/images/8.jpg',
        'title' => 'Our Hygiene Standards for Fruit Packing',
        'meta1' => 'Fruitwala',
        'meta2' => 'Safety First',
        'link' => '#',
    ],
    'gallery_side_4' => [
        'thumb' => 'assets/images/10.jpg',
        'title' => 'Top Immunity Boosting Fruits You Should Eat',
        'meta1' => 'Fruitwala',
        'meta2' => 'Nutrition',
        'link' => '#',
    ],
    'service_1' => [
        'title' => 'Fast Home Delivery',
        'subtitle' => 'Fresh fruits delivered to your doorstep',
        'icon' => 'fas fa-shipping-fast',
    ],
    'service_2' => [
        'title' => 'Premium Quality Fruits',
        'subtitle' => 'Handpicked & carefully packed',
        'icon' => 'fas fa-apple-alt',
    ],
    'service_3' => [
        'title' => 'Custom Fruit Baskets',
        'subtitle' => 'Perfect for gifts & special occasions',
        'icon' => 'fas fa-box-open',
    ],
    'service_4' => [
        'title' => 'Customer Support',
        'subtitle' => 'We’re here to help you anytime',
        'icon' => 'fas fa-headset',
    ],
    'instagram' => [
        'heading' => 'Follow Fruitwala Breakfast on Instagram',
        'handle' => '@fruitwala_breakfast',
    ],
    'ig_1' => ['popup' => 'assets/images/5.jpg', 'img' => 'assets/images/5.jpg', 'alt' => 'Fruit Basket'],
    'ig_2' => ['popup' => 'assets/images/7.jpg', 'img' => 'assets/images/7.jpg', 'alt' => 'Fresh Fruit Box'],
    'ig_3' => ['popup' => 'assets/images/8.jpg', 'img' => 'assets/images/8.jpg', 'alt' => 'Gift Fruit Basket'],
    'ig_4' => ['popup' => 'assets/images/9.jpg', 'img' => 'assets/images/9.jpg', 'alt' => 'Premium Fruit Hamper'],
    'ig_5' => ['popup' => 'assets/images/10.jpg', 'img' => 'assets/images/10.jpg', 'alt' => 'Healthy Fruit Gift'],
];
